package com.example.fruitbox

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Toast
import androidx.appcompat.widget.SearchView
import com.example.fruitbox.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    private lateinit var binding: ActivityMainBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val nameFruit = arrayOf(
            "Apel", "Pisang", "Jeruk", "Mangga", "Anggur", "Semangka", "Nanas", "Strawberry", "Ceri", "Persik", "Pir", "Raspberry", "Blackberry", "Blueberry", "Lemon", "Alpukat", "Kiwi"
        )

        val fruitAdapter : ArrayAdapter<String> = ArrayAdapter<String>(
            this,
            android.R.layout.simple_list_item_1,
            nameFruit
        )

        binding.searchView.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
            override fun onQueryTextSubmit(query: String?): Boolean {
                binding.searchView.clearFocus()
                if (nameFruit.contains(query)) {
                    fruitAdapter.filter.filter(query)
                }
                return false
            }

            override fun onQueryTextChange(newText: String?): Boolean {
                fruitAdapter.filter.filter(newText)
                return false
            }
        })


        val adapterFruit = FruitAdapter(generateFruitData()) { fruit ->
            val intent = Intent(this@MainActivity, DetailActivity::class.java)
            intent.putExtra("FRUIT_NAME", fruit.name)
            intent.putExtra("FRUIT_PRICE", fruit.price)
            intent.putExtra("FRUIT_IMAGE", fruit.image)
            intent.putExtra("FRUIT_DESCRIPTION", fruit.description)
            startActivity(intent)
        }

        with(binding) {
            rvFruit.apply {
                adapter = adapterFruit
                layoutManager = androidx.recyclerview.widget.LinearLayoutManager(this@MainActivity)
            }
        }
    }


    fun generateFruitData(): List<Fruit> {
        return listOf(
            Fruit("Apel", "10$", R.drawable.apple, "Apel adalah buah yang berasal dari pohon buah apel (Malus domestica) dan termasuk ke dalam keluarga Rosaceae. Buah apel memiliki bentuk bulat dengan kulit yang halus dan berbagai warna, mulai dari merah, hijau, hingga kuning. Daging buah apel umumnya renyah dan manis, meskipun beberapa varietas juga memiliki rasa sedikit asam. Buah apel dikenal sebagai salah satu buah yang paling populer di seluruh dunia. Buah ini memiliki banyak varietas, masing-masing dengan karakteristik uniknya sendiri. Apel sering dimakan segar, tetapi juga digunakan dalam berbagai hidangan, minuman, dan produk makanan lainnya seperti jus, saus, dan pai. Buah apel mengandung serat makanan, vitamin C, kalium, dan antioksidan. Serat makanan dalam apel dapat membantu meningkatkan pencernaan dan menjaga kesehatan usus. Vitamin C adalah antioksidan penting yang mendukung sistem kekebalan tubuh. Kalium adalah mineral yang penting untuk menjaga tekanan darah yang sehat. Selain kandungan nutrisi, buah apel juga memiliki sejarah dan mitologi yang kaya. Apel sering kali dianggap sebagai simbol pengetahuan, kebijaksanaan, dan keabadian dalam berbagai budaya dan cerita rakyat. Buah apel juga menjadi bagian dari berbagai perayaan dan festival di berbagai negara di seluruh dunia. Namun, sangat penting untuk mencuci apel dengan baik sebelum dimakan atau dimasak untuk menghilangkan kotoran dan pestisida yang mungkin melekat pada kulitnya. Apel yang sehat dan segar adalah pilihan camilan yang lezat dan bergizi untuk menambah variasi diet sehari-hari."),
            Fruit("Pisang", "8$", R.drawable.bananas, "Pisang, buah tropis berkulit kuning yang familiar bagi banyak orang, bukan hanya memanjakan lidah dengan rasa manisnya yang luar biasa, tetapi juga menyembunyikan kandungan nutrisi yang sangat baik untuk kesehatan. Kaya akan potassium, vitamin C, vitamin B6, dan serat makanan, pisang tidak hanya memberikan energi yang stabil dan bertahap berkat karbohidrat kompleksnya, tetapi juga mendukung kesehatan jantung, fungsi otot, dan sistem kekebalan tubuh. Serat makanan dalam pisang mendukung pencernaan yang sehat, sementara vitamin B6 membantu menjaga sistem saraf tetap berfungsi dengan baik. Pisang juga dikenal membantu mengurangi risiko penyakit jantung, menstabilkan tekanan darah, dan meningkatkan suasana hati berkat kandungan triptofannya. Tidak hanya cocok sebagai camilan yang praktis, pisang juga sering dijadikan bahan untuk berbagai hidangan, dari roti pisang hingga smoothie, menambahkan sentuhan kelezatan dan gizi dalam setiap sajian. Dengan segala manfaat kesehatan dan kelezatannya, pisang menjadi pilihan cerdas untuk memperkaya pola makan sehari-hari dengan kebaikan alam yang memukau."),
            Fruit("Jeruk", "7$", R.drawable.orange, "Jeruk, dengan keindahan warna oranye menyala pada kulitnya yang tebal, adalah buah yang menggoda dengan rasa manis dan asamnya yang khas. Buah ini berasal dari keluarga Rutaceae dan memiliki banyak jenis varietas, mulai dari jeruk manis, jeruk nipis, hingga jeruk keprok. Kulit jeruk yang tebal mengandung minyak esensial yang memberi aroma segar dan menyegarkan saat diiris atau diperas. Jeruk adalah sumber yang kaya akan vitamin C, yang tidak hanya memperkuat sistem kekebalan tubuh, tetapi juga memberi kulit kecerahan dan kelembapan alami. Selain vitamin C, jeruk juga mengandung senyawa flavonoid seperti hesperidin dan naringin, yang memiliki sifat antioksidan dan antiinflamasi. Serat makanan dalam jeruk membantu pencernaan yang sehat dan menjaga kadar gula darah tetap stabil. Jeruk juga mengandung kalium, mineral yang mendukung fungsi otot dan jantung yang sehat. Baunya yang segar dan rasa asam manisnya membuat jeruk menjadi pilihan yang populer tidak hanya sebagai buah segar, tetapi juga dalam berbagai hidangan, minuman, dan kue-kue. Jeruk bukan hanya sekadar buah, melainkan juga simbol kesegaran dan keceriaan dalam setiap sajian."),
            Fruit("Mangga", "15$", R.drawable.mango, "Buah mangga adalah salah satu buah tropis yang sangat populer di seluruh dunia, terkenal karena rasa manisnya yang lezat dan teksturnya yang lembut. Mangga berasal dari pohon Mangifera indica dan telah menjadi bagian integral dari budaya dan kuliner di banyak negara tropis. Buah ini memiliki bentuk oval atau bulat dengan kulit yang halus dan warna yang bervariasi, mulai dari hijau muda hingga kuning cerah atau oranye saat matang. Daging buah mangga memiliki warna kuning, oranye, atau merah, tergantung pada varietasnya.\n" +
                    "\n" +
                    "Selain kelezatannya, mangga juga dikenal karena kandungan nutrisinya yang kaya. Buah ini mengandung vitamin A, C, dan E, yang penting untuk kesehatan kulit, penglihatan, dan sistem kekebalan tubuh. Mangga juga merupakan sumber serat makanan yang baik, membantu menjaga pencernaan yang sehat dan mencegah sembelit. Selain itu, mangga mengandung senyawa antioksidan seperti quercetin, astragalin, dan fisetin, yang membantu melawan radikal bebas dalam tubuh, mendukung kesehatan jantung, dan mengurangi risiko penyakit kronis.\n" +
                    "\n" +
                    "Tidak hanya buahnya yang lezat, namun juga berbagai produk turunan mangga yang populer, seperti jus mangga, selai mangga, atau bahkan mangga yang diawetkan. Buah mangga juga memiliki nilai budaya yang tinggi dalam banyak masyarakat tropis, sering kali dianggap sebagai simbol keberlimpahan dan keberuntungan. Oleh karena itu, mangga tidak hanya memanjakan lidah dengan rasa manisnya yang eksotis, tetapi juga memberikan berbagai manfaat kesehatan dan kegembiraan bagi para pencinta buah di seluruh dunia."),
            Fruit("Anggur", "12$", R.drawable.grape, "Buah anggur, dengan keindahan bentuknya yang bulat dan warnanya yang menggoda, adalah salah satu buah yang paling disukai di seluruh dunia. Anggur tumbuh dalam berbagai varietas, masing-masing memiliki karakteristik uniknya sendiri. Baik yang berwarna merah, hijau, maupun ungu, anggur memiliki rasa manis yang lezat dan tekstur yang kenyal. Di balik kenikmatan rasanya, anggur juga mengandung sejumlah besar senyawa fitokimia, termasuk polifenol dan flavonoid, yang dikenal memiliki sifat antioksidan dan antiinflamasi. Senyawa-senyawa ini memberikan manfaat kesehatan yang luar biasa, termasuk melindungi sel-sel tubuh dari kerusakan oksidatif dan mendukung kesehatan jantung. Selain itu, anggur juga mengandung resveratrol, sejenis polifenol yang ditemukan terutama pada kulit anggur merah. Resveratrol telah dikaitkan dengan berbagai manfaat kesehatan, termasuk melindungi jantung, mengurangi risiko penyakit kronis, dan mendukung proses penuaan yang sehat. Selain kandungan nutrisinya yang kaya, anggur juga merupakan bagian dari budaya dan tradisi banyak masyarakat di seluruh dunia. Dari anggur juga dihasilkan produk yang sangat dihargai, seperti anggur menjadi bahan dasar dalam pembuatan wine, memberikan sentuhan keanggunan dan kenikmatan tersendiri."),
            Fruit("Semangka", "20$", R.drawable.watermelon, "Semangka adalah buah yang menjadi favorit di musim panas, tidak hanya karena rasa manisnya yang menyegarkan, tetapi juga karena kandungan nutrisi yang kaya dan manfaat kesehatan yang luar biasa. Buah semangka memiliki tekstur yang juicy dan kandungan air yang tinggi, menjadikannya buah yang sangat cocok untuk menjaga tubuh terhidrasi di musim panas. Warna merah cerah pada daging buah semangka menunjukkan keberadaan likopen, sejenis antioksidan yang memiliki peran penting dalam melawan radikal bebas dalam tubuh, serta membantu mengurangi risiko penyakit jantung dan kanker. Selain itu, semangka juga mengandung citrulline, senyawa yang membantu meningkatkan aliran darah dan mendukung kesehatan jantung. Kandungan vitamin C dalam semangka mendukung sistem kekebalan tubuh, sementara vitamin A menjaga kesehatan mata. Tidak hanya buahnya yang lezat, bahkan bijinya juga dapat dimanfaatkan. Bijinya mengandung protein, serat, dan asam lemak omega-3 yang baik untuk kesehatan jantung dan pencernaan. Dengan rasa manisnya yang menyegarkan dan manfaat kesehatannya yang melimpah, semangka tidak hanya menjadi pilihan camilan yang enak di musim panas, tetapi juga membawa berbagai kebaikan bagi kesehatan tubuh."),
            Fruit("Nanas", "17$", R.drawable.pineapple, "Buah nanas, dengan rasa manis dan asamnya yang khas, adalah salah satu buah tropis yang sangat populer di seluruh dunia. Buah ini memiliki bentuk bulat dengan kulit tebal yang berwarna hijau kekuningan, dan dagingnya yang kuning cerah terletak di dalamnya. Nanas mengandung berbagai nutrisi penting, termasuk vitamin C, mangan, vitamin B6, dan serat makanan. Kandungan vitamin C dalam nanas sangat tinggi, membantu memperkuat sistem kekebalan tubuh, mendukung kesehatan kulit, dan memperbaiki sel-sel tubuh yang rusak. Selain itu, mangan dalam nanas adalah mineral penting yang berperan dalam pembentukan tulang, pembekuan darah, dan pengaturan gula darah. Vitamin B6 juga ditemukan dalam jumlah cukup dalam nanas, mendukung fungsi saraf yang sehat dan metabolisme energi.\n" +
                    "\n" +
                    "Namun, buah nanas bukan hanya lezat, tetapi juga memiliki manfaat kesehatan yang luar biasa. Nanas mengandung enzim bromelain, yang memiliki sifat antiinflamasi dan membantu pencernaan protein. Oleh karena itu, nanas sering digunakan dalam pengobatan tradisional untuk mengurangi peradangan dan mendukung pencernaan yang sehat. Buah nanas juga dikenal karena kandungan seratnya yang tinggi, membantu menjaga pencernaan lancar dan mengurangi risiko masalah pencernaan seperti sembelit.\n" +
                    "\n" +
                    "Selain manfaat kesehatan, nanas sering dijadikan bahan dalam berbagai hidangan, mulai dari smoothie, salad buah, hingga kue dan masakan. Aroma segar nanas seringkali membuatnya menjadi pilihan utama dalam minuman segar, jus, dan koktail. Buah nanas juga dapat diawetkan dalam bentuk kaleng atau diolah menjadi selai dan saus. Kombinasi rasa manis dan segar nanas membuatnya menjadi camilan yang menyegarkan dan bergizi, menjadikannya salah satu buah yang paling dicari dan dinikmati oleh banyak orang di seluruh dunia."),
            Fruit("Strawberry", "16$", R.drawable.strawberry, "Strawberry, buah merah manis yang kecil namun penuh dengan kebaikan bagi kesehatan. Dikenal dengan namanya yang menggemaskan, buah ini tidak hanya memanjakan lidah kita tetapi juga memberikan sejumlah manfaat yang luar biasa. Strawberry kaya akan vitamin C, suatu antioksidan yang penting untuk melawan radikal bebas dalam tubuh dan mendukung sistem kekebalan tubuh agar tetap kuat. Selain itu, buah ini mengandung anthocyanin, senyawa yang memberi warna merah pada strawberry dan memiliki efek antioksidan yang kuat, membantu melindungi sel-sel tubuh dari kerusakan. Selain antioksidan, strawberry juga mengandung serat makanan, yang mendukung pencernaan yang sehat dan membantu mengontrol kadar gula darah. Buah ini juga mengandung folat, kalium, dan mangan, yang penting untuk fungsi tubuh yang optimal. Tak hanya sehat, strawberry juga membuat berbagai hidangan dan minuman menjadi lebih segar dan lezat. Dari smoothie hingga saus, kehadiran strawberry selalu meningkatkan rasa dan tampilan setiap hidangan. Dengan citarasa manisnya yang khas dan beragam manfaat kesehatan, strawberry bukan hanya sekadar buah, melainkan pilihan makanan yang cerdas dan lezat bagi semua orang."),
            Fruit("Ceri", "11$", R.drawable.cherries, "Buah ceri, dengan kecantikan warna merahnya yang menggoda, adalah salah satu buah beri yang sangat dihargai karena rasa manis dan asamnya yang seimbang. Ceri, juga dikenal dengan nama Prunus avium atau ceri manis, memiliki ukuran kecil dengan kulit halus yang melindungi daging buahnya yang lembut. Kekhasan ceri terletak pada rasa manis yang segar dan sentuhan keasamannya yang menyegarkan, menciptakan sensasi rasa yang memukau saat pertama kali digigit. Selain kelezatannya, ceri juga kaya akan nutrisi. Buah ini mengandung antioksidan kuat seperti anthocyanin, quercetin, dan vitamin C, yang membantu melawan radikal bebas dalam tubuh dan mendukung sistem kekebalan tubuh. Selain itu, ceri juga mengandung serat makanan, yang penting untuk pencernaan yang sehat, serta zat besi dan potassium, yang mendukung kesehatan jantung dan pembentukan sel darah merah. Ceri juga memiliki sifat antiinflamasi dan dapat membantu mengurangi risiko penyakit jantung serta memperbaiki kualitas tidur. Sebagai buah yang serbaguna, ceri dapat dinikmati segar, dijadikan tambahan dalam hidangan pencuci mulut, atau diolah menjadi selai, saus, atau minuman segar. Kelembutan dan kelezatan ceri membuatnya menjadi pilihan camilan sehat yang sangat diinginkan oleh banyak orang, sementara manfaat kesehatannya menjadikannya salah satu buah yang sangat bernilai dalam menjaga kesejahteraan tubuh."),
            Fruit("Persik", "9$", R.drawable.peach, "Buah persik, yang memiliki nama ilmiah Prunus persica, adalah buah yang sangat dicintai dengan kulit halus yang berwarna oranye atau kuning dan daging yang sangat manis dan lembut. Buah ini berasal dari Asia dan telah menjadi bagian integral dari berbagai budaya di seluruh dunia. Persik dikenal karena kelembutannya yang memikat dan rasa manisnya yang memanjakan lidah. Selain kelezatannya, persik juga kaya akan nutrisi. Buah persik mengandung vitamin C yang penting untuk meningkatkan sistem kekebalan tubuh, serta vitamin A yang mendukung kesehatan mata dan kulit. Selain itu, persik juga mengandung serat makanan, yang membantu menjaga pencernaan tetap sehat dan mengurangi risiko masalah pencernaan seperti sembelit. Buah persik juga mengandung senyawa antioksidan, seperti beta-karoten dan flavonoid, yang membantu melawan radikal bebas dalam tubuh, mendukung kesehatan jantung, dan mengurangi risiko penyakit kronis. Dalam segala kelembutannya, persik tidak hanya memberikan kenikmatan bagi lidah tetapi juga memberikan manfaat kesehatan yang luar biasa bagi tubuh, menjadikannya pilihan buah yang ideal untuk dinikmati segar atau digunakan dalam berbagai hidangan dan makanan penutup yang lezat."),
            Fruit("Pir", "10$", R.drawable.pear, "Buah pir, yang dikenal dengan nama ilmiah Pyrus, adalah buah dengan kulit halus dan daging yang lembut serta manis. Buah ini berasal dari pohon pir, yang termasuk dalam keluarga Rosaceae. Pir sering memiliki warna kulit hijau atau kuning, tergantung pada jenisnya. Tekstur dagingnya yang lembut dan rasanya yang manis membuatnya menjadi buah yang disukai banyak orang. Pir kaya akan serat makanan, yang membantu meningkatkan pencernaan dan menjaga kesehatan usus. Selain itu, pir juga mengandung vitamin C, yang mendukung sistem kekebalan tubuh, serta vitamin K, yang penting untuk pembekuan darah yang sehat. Mineral seperti potassium juga ditemukan dalam jumlah yang cukup dalam pir, membantu menjaga tekanan darah yang stabil. Buah pir sering dimakan segar, tetapi juga sering digunakan dalam berbagai hidangan, mulai dari pai, selai, hingga salad, menambahkan rasa manis dan kelezatan pada setiap hidangan. Kombinasi antara rasa manis dan tekstur yang renyah membuat pir menjadi buah yang populer di meja makan, serta pilihan yang sehat untuk camilan sehari-hari."),
            Fruit("Raspberry", "13$", R.drawable.raspberry, "Raspberry, atau biasa disebut dengan raspberry merah, adalah buah berwarna merah yang menggoda dengan rasa manis dan sedikit asamnya. Buah ini merupakan sumber antioksidan yang kaya, terutama anthocyanin, quercetin, dan vitamin C, yang menjadikannya pelindung alami tubuh dari radikal bebas dan kerusakan sel. Raspberry juga kaya akan serat makanan, yang mendukung pencernaan sehat dan membantu mengurangi risiko masalah pencernaan seperti sembelit. Selain itu, buah raspberry mengandung senyawa fenolik, flavonoid, dan asam ellagic, yang memiliki sifat antiinflamasi dan dapat membantu mengurangi risiko penyakit jantung. Raspberry juga mengandung zat besi, magnesium, dan kalium, yang penting untuk menjaga keseimbangan elektrolit tubuh. Selain manfaat kesehatan, raspberry sering digunakan dalam berbagai hidangan pencuci mulut, selai, saus, dan minuman segar, menambahkan sentuhan rasa yang lezat dan sehat pada makanan sehari-hari. Dengan kombinasi rasa yang nikmat dan manfaat kesehatannya yang luar biasa, raspberry menjadi pilihan buah yang populer dan dicari untuk meningkatkan gaya hidup sehat."),
            Fruit("Blackberry", "14$", R.drawable.blackberry, "Blackberry, atau yang dikenal juga dengan nama rubus fruticosus, adalah buah beri yang tumbuh pada semak-semak berduri dan merambat. Buah ini memiliki warna gelap yang menggoda dan rasa manis yang khas. Blackberry kaya akan nutrisi, terutama serat makanan, vitamin C, dan antioksidan. Serat makanan dalam blackberry mendukung pencernaan yang sehat, membantu mengurangi risiko sembelit, dan menjaga kesehatan usus. Selain itu, kandungan vitamin C dalam buah ini mendukung sistem kekebalan tubuh, membantu melawan infeksi, dan meningkatkan kesehatan kulit. Antioksidan dalam blackberry, seperti flavonoid dan polifenol, melindungi sel-sel tubuh dari kerusakan akibat radikal bebas, yang dapat mengurangi risiko penyakit kronis seperti kanker dan penyakit jantung. Blackberry juga mengandung anthocyanin, senyawa yang memberi warna gelap pada buah ini dan memiliki efek antiinflamasi serta melindungi kesehatan jantung. Dengan kandungan nutrisi yang melimpah, blackberry tidak hanya menawarkan cita rasa lezat, tetapi juga memberikan manfaat kesehatan yang signifikan bagi tubuh."),
            Fruit("Blueberry", "15$", R.drawable.blueberries, "Blueberry, atau dikenal sebagai buah bluberry, adalah buah kecil berwarna biru yang tumbuh pada semak-semak rendah dari genus Vaccinium. Buah ini terkenal karena rasa manisnya yang khas dan memiliki tekstur yang lembut saat dimakan. Blueberry mengandung senyawa-senyawa aktif yang sangat baik untuk kesehatan. Mereka adalah sumber antioksidan yang kaya, terutama dalam bentuk flavonoid seperti antosianin, yang memberikan warna biru pada buah ini. Antioksidan ini memiliki peran penting dalam melawan radikal bebas dalam tubuh, membantu melindungi sel-sel dari kerusakan dan mengurangi risiko berbagai penyakit kronis, termasuk penyakit jantung dan kanker. Selain itu, blueberry juga mengandung vitamin C, K, dan serat makanan, mendukung sistem kekebalan tubuh, pembekuan darah yang sehat, dan pencernaan yang lancar. Beberapa penelitian juga menunjukkan bahwa konsumsi blueberry secara teratur dapat meningkatkan fungsi otak dan memperbaiki daya ingat, membuatnya menjadi pilihan camilan sehat yang populer dan bergizi."),
            Fruit("Lemon", "16$", R.drawable.lemon, "Buah lemon, dengan warnanya yang cerah dan rasa asam yang khas, adalah salah satu buah sitrus yang sangat dikenal dan digunakan di seluruh dunia. Lemon memiliki kulit yang tebal dan kasar dengan warna kuning cerah, sementara dagingnya yang berair dan asam sering digunakan untuk memberikan rasa segar pada berbagai hidangan dan minuman. Kandungan vitamin C dalam lemon sangat tinggi, menjadikannya sumber antioksidan yang kuat yang mendukung sistem kekebalan tubuh dan membantu melawan radikal bebas dalam tubuh. Selain itu, lemon juga mengandung flavonoid, senyawa fitokimia yang memiliki efek antiinflamasi dan antikanker. Lemon juga dikenal karena kandungan seratnya yang membantu pencernaan dan menjaga kesehatan usus. Minuman hangat air lemon sering kali diandalkan sebagai ramuan penyegar dan pembersih tubuh yang alami, memberikan manfaat detoksifikasi dan membersihkan sistem pencernaan. Selain digunakan dalam minuman, lemon juga sering digunakan dalam masakan dan hidangan pencuci mulut untuk memberikan sentuhan segar dan asam yang menyegarkan. Dengan kombinasi khasiat kesehatannya dan rasa yang unik, lemon tidak hanya memberikan sensasi kuliner yang istimewa tetapi juga menyediakan berbagai manfaat bagi kesehatan tubuh."),
            Fruit("Alpukat", "17$", R.drawable.avocado, "Alpukat, yang juga dikenal sebagai \"pear butter\" atau \"alligator pear,\" adalah buah yang memiliki kulit hijau dan daging yang lembut serta kaya akan nutrisi. Buah ini tumbuh pada pohon alpukat (Persea americana), yang berasal dari Meksiko, Amerika Tengah, dan Amerika Selatan. Alpukat dikenal sebagai sumber lemak sehat, terutama asam lemak tak jenuh tunggal, yang baik untuk kesehatan jantung. Selain itu, alpukat juga mengandung banyak serat makanan, yang membantu pencernaan dan membuat Anda merasa kenyang lebih lama. Buah ini juga mengandung berbagai nutrisi penting seperti potassium, vitamin K, vitamin E, vitamin C, dan vitamin B-6. Potassium dalam alpukat membantu menjaga tekanan darah tetap stabil dan mendukung fungsi otot yang sehat. Selain kandungan nutrisi yang kaya, alpukat juga sering digunakan dalam berbagai hidangan, mulai dari salad, guacamole, hingga smoothie. Rasanya yang khas, lembut, dan sedikit kreami membuat alpukat menjadi favorit di dunia kuliner, tidak hanya untuk rasanya yang lezat, tetapi juga manfaat kesehatannya yang luar biasa."),
            Fruit("Kiwi", "18$", R.drawable.kiwi, "Alpukat, yang juga dikenal sebagai \"pear butter\" atau \"alligator pear,\" adalah buah yang memiliki kulit hijau dan daging yang lembut serta kaya akan nutrisi. Buah ini tumbuh pada pohon alpukat (Persea americana), yang berasal dari Meksiko, Amerika Tengah, dan Amerika Selatan. Alpukat dikenal sebagai sumber lemak sehat, terutama asam lemak tak jenuh tunggal, yang baik untuk kesehatan jantung. Selain itu, alpukat juga mengandung banyak serat makanan, yang membantu pencernaan dan membuat Anda merasa kenyang lebih lama. Buah ini juga mengandung berbagai nutrisi penting seperti potassium, vitamin K, vitamin E, vitamin C, dan vitamin B-6. Potassium dalam alpukat membantu menjaga tekanan darah tetap stabil dan mendukung fungsi otot yang sehat. Selain kandungan nutrisi yang kaya, alpukat juga sering digunakan dalam berbagai hidangan, mulai dari salad, guacamole, hingga smoothie. Rasanya yang khas, lembut, dan sedikit kreami membuat alpukat menjadi favorit di dunia kuliner, tidak hanya untuk rasanya yang lezat, tetapi juga manfaat kesehatannya yang luar biasa."),

            )
    }
}